### ISSUE TITLE
Live Stream fails

### ISSUE THREAD

**Issue by BigTons** [aussieaddons/plugin.video.afl-video#2625]
Hi, 
Just recently downloaded the addon on Windows.

Appear to be getting a 404 error when selecting live games (replays work fine).

Error report 4989.

Thanks in advance.

**Comment by glennguy** [comment]
Hi @BigTons

Thanks for the log. This one should be straight forward to fix. It's usually caused by your system clock being a little bit out of sync. Looking at the time the log came in vs the time it was sent in the log it seems you're running a minute fast give or take. 

Just go into your time/date settings in windows and make sure it's set to sync automatically. If it is already, turn it off and back on again.

Let us know how you get on

Glenn

**Comment by BigTons** [comment]
Thanks @glennguy, seeing some progress with that fix (although the solution was just a manual adjustment of the clock back 1min... not sure if that is appropriate?)

Live games are now loading however only audio and the display lags leaving a trail of the cursor (see attached). This only applies for live streaming. I ran a follow up log (5000).

Hoping you have a solution for this one as simple as the last. Thought this might have been something to do with Settings>Player>Video>Processing> Hardware acceleration (per this thread https://github.com/aussieaddons/plugin.video.afl-video/issues/2614#issuecomment-475812337) but i've toggled this on and off and makes no change.

![Kodi Error](https://user-images.githubusercontent.com/50258399/58744902-3a4e2b00-848c-11e9-9a65-7d0dc257d0f6.png)

**Comment by glennguy** [comment]
I think it's still the clock. You're still in the future a little bit from the looks of it - the segments are 404 for the first couple of tries then they download. That's also possibly linked to the audio issue as the audio and video come in separate segments. Try winding your clock back another 30 seconds and try again.

**Comment by BigTons** [comment]
Yep spot on! Thats fixed it perfectly.

The future seems like an awful place tbh. Think ill stick with the present.

Thanks for your help.

**Comment by glennguy** [comment]
Haha too right. Happy to help, glad it's all working now!
