### ISSUE TITLE
AFL Video 1.9.2-3~g3e2e499 won't open

### ISSUE THREAD

**Issue by bosman101** [aussieaddons/plugin.video.afl-video#2631]
AFL Video won't open, just errors to see kodi log for more info.
Tried on 2 android boxes both doing the same. installed a clean version of kodi 18.3 on a windows machine and then installed afl video and same issue, won't open.
attaching log from Windows machine.

Thanks

[kodi.log](https://github.com/aussieaddons/plugin.video.afl-video/files/3511405/kodi.log)

**Comment by glennguy** [comment]
Hey @bosman101 

Thanks for raising this issue, I think I've fixed it if you want to test. The issue was caused by a missing dependency in the drmhelper addon that afl-video requires.

To force update it, go into addons, click the setup/open box icon, install from repository, then bring up the context menu for our development repo and chose 'check for updates'. You can confirm it is installed by going into settings > system > addons > manage dependencies and DRM Helper should be 2.0.0-8~g7638906

Let us know if you have anymore problems :)

**Comment by bosman101** [comment]
Hi glennguy 
Thanks for the prompt response.
Got it working on the windows device after update. Great work.
Since I deleted kodi on the android device I'm having issues installing some of the dependencies as they are not available or missing. I will look into later.
Thanks again..

**Comment by larryhudson** [comment]
Hi, I've got a Raspberry Pi 3B running LibreElec, and AFL Video was working fine up until a couple of days ago. Last night I was having the same issue as above (the addon not loading at all).

I've updated the dependencies,and now DRM Helper is version 2.0.0.9-gffe6b8f (newer than the version mentioned above).

Now it is loading the plugin menus but I'm getting the following message when I try to play a live match:
"Platform not supported
Linux (armv7) not supported for DRM playback. For more information, see our DRM FAQ"

Thanks for all your work, it's a great addon!

**Comment by glennguy** [comment]
hi @larryhudson 

Sorry about this, I'll get it sorted straight away

**Comment by glennguy** [comment]
@larryhudson 
Fixed, please update drmhelper to 2.0.0.10 and let us know how you go!

**Comment by bosman101** [comment]
@glenn,
I've got this working now on both Android and Windows with the new drmhelper.
Thanks allot for your help and quick turnaround.

**Comment by larryhudson** [comment]
@glennguy Thanks very much, it's working on the Raspberry Pi too. Thanks for fixing it so quickly.
