### ISSUE TITLE
Stored token expired for AFL live pass

### ISSUE THREAD

**Issue by robmOz** [aussieaddons/plugin.video.afl-video#2632]
Hi, I just installed Kodi and Aussie add ons.

I am getting the same error as  previous Issue 2630. (Only difference is line is now play.py(48) )

Is there a fix?

https://github.com/aussieaddons/plugin.video.afl-video/issues/2630

Update: this started to work just after I posted the issue. Before the problem resolved itself I turned off debug logging, however, I think the most logical explanation for why it suddenly started working was something on Telstra's end? Will leave issue open for now and close it after bit of testing.

**Comment by glennguy** [comment]
Hey @robmOz 

Thanks for the update.

The message 'Stored token expired' probably needs to be changed. It *can* mean that, but we're now realising that sometimes it is just an issue on Telstra's end. As I mentioned in #2630 we have seen issues in the past caused by having non-mobile services such as home phone/broadband attached to a Telstra ID, but I have no idea whether that has been fixed or not, or if there's a new issue we don't know about. One thing for certain was that it couldn't be fixed on our end :(

The one way to know for sure who's at fault is to try logging in on the mobile app over wifi (don't let it use the mobile network to activate). In #2630 we couldn't get the live pass activated that way, which says it's on Telstra's end.

**Comment by robmOz** [comment]
@glennguy thanks for the info. Problem not occurring anymore. It was just that one time after the initial install where I was on my tablet so using wifi only. Then I think I activated the pass on the phone after installing AFL app on the phone. Problem on Telstra's end. Thanks for your help. Closing issue.
