### ISSUE TITLE
bad colours and pixelation on live tv

### ISSUE THREAD

**Issue by monty974** [aussieaddons/plugin.video.afl-video#2643]
I've noticed on the live afl.tv feed the colours are all wrong and the pixellation is all over the place. the replays are ok but the live is not. I am not sure if the other live feeds will be the same next week or if something has changed, but I also asked someone else to confirm and they get the same result.

**Comment by glennguy** [comment]
Hi @monty974 I've just had a look and can confirm. If you want a work around for the time being you can set the stream selection to manual in inputstream.adaptive settings, then use the OSD video settings menu to change the stream once playback has begun - choose hevc 9/10 one to get the same quality but without the messed up colors. As long as your device isn't a toaster it should be able to keep up with decoding that.

**Comment by monty974** [comment]
thanks @glennguy, i tried that but my raspberry Pi kept crashing every time I changed it.. It's a V4 model and i just re-built the OS from scratch so not sure why it was crashing.

**Comment by glennguy** [comment]
I've done some very quick research. Are you using 64 bit OS or 32?

**Comment by monty974** [comment]
It’s the rp4.arm on raspberry pi.

**Comment by glennguy** [comment]
The reason I ask is it looks like hardware hevc decoding seems to have limited if at all any support on 64 bit userland OS with rpi4. If you're running raspbian 64bit then this is likely the case.

LibreELEC though seems to have it sorted. Plus being 32 bit userland means you can view widevine DRM protected streams (disney+, netflix, some 9now shows etc.) which for now is impossible under 64bit

**Comment by Flamples** [comment]
"LibreELEC though seems to have it sorted."

Not so. I have been trying to watch the footy for three days using LibreElec on a RPi and all I'm getting is pixellation and crazy colours. I don't remember taking that acid! Frustrating, because the game I actually want to watch is on in half an hour.

I have been checking for an AFL Addon update periodically over the last few days, but nothing forthcoming. I have diddled with meagre range of settings in the video settings while the vid was playing to no effect.

I would imagine this is officially an issue, but strange how there's only three of us here and only two of us who are experiencing it. Must be more than that out there.

**Comment by glennguy** [comment]
> "LibreELEC though seems to have it sorted."

@Flamples this remark was relating to the issue that @monty974 had with HEVC streams crashing on rpi4 (non LibreELEC), nothing to do with the color/pixelation.

As mentioned above, the workaround is to select a HEVC encoded video stream.
Steps to do this are:
* open AFL addon settings and select the video quality/inputstream adaptive settings
* within these settings, change stream selection from auto to manual
* play a live stream within AFL addon
* bring up the osd (press enter on keyboard/click ok on remote/press screen on touch device)
* select the cog/settings icon
* select video settings
* the top item should be the video stream, open this and select the best HEVC stream available (should be stream 9/10)
* ?????
* profit

There's no real fix for the h264 streams, the issue is on Telstra/AFL's end. The h264 streams look blocky and weird colors when playing them in a browser or VLC, so to me that says the problem is nothing to do with Kodi or this addon.

I'm sure there will be a lot more reports of this once matches resume. It may not yet have been brought to Telstra's attention as most android/ios devices should be capable of HEVC decoding therfore they don't end up seeing the buggy streams. Hopefully they do notice this and the issue gets resolved at the source.

**Comment by monty974** [comment]
Two points to add.. my RP4 is Libelec as the OS.

Also the NRL live feed last night was fine so perhaps it’s just the live.tv stream?

**Comment by glennguy** [comment]
Like I said the h264 streams from AFL seem to be decoding fine (no ffmpeg errors in Kodi), so as far as the decoder is concerned that's exactly how the stream is supposed to look. The issue is somewhere on Telstra's end.

I've also just tested on Exoplayer in Android and confirmed the issue is the same there.

I'm not sure what the situation was the other day but right now it appears to only be affecting the 1024*576 h264 stream (stream 10/10), all other h264 streams seem fine.

**Comment by glennguy** [comment]
Issue now appears to be resolved from Telstra's end
